version: '3.8'

services:
  uniwaf:
    image: registry.jxit.net.cn:5000/microflow/stix-spark:git-9
    container_name: unistix
    environment:
      LISTEN_PORT: 15155
      OUTPUT: 127.0.0.1:12201
    command:
    - "sh"
    - "-xc"
    - | 
      unistix -l $${LISTEN_PORT} -m stix-file/result -s $${OUTPUT} -p 127.0.0.1 -r
